Lower grass target in standalone economy tests
because: The test_economy_moderate_standalone was failing tests on
arm64 MacOS systems with the following error:

```
thread 'site::economy::context::tests::test_economy_moderate_standalone' panicked at 'assertion failed: site.economy.pop >= env.targets[&id]', world/src/site/economy/context.rs:562:17
```

This was originally reported in Discord by @sharp in July, 2022
https://discord.com/channels/449602562165833758/797421546871324712/997332351195553874

Debugging showed that the grass target was 880, and the population was only around 718.
Local testing showed that lowering the grass target to 700 fixed the issue.

this commit: Lowers the grass target to 700 in the standalone economy tests.

unaddressed questions:

- Why is the grass target so high in the standalone economy tests?
- Alternately, why did the grass population drift so low, and no longer aligned with the tests.
- Why is this passing in CI, but not local testing?
- There are a number of commented out add_settlement calls in the standalone economy tests. Were there issues with the tests prior?